apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: venkataveerakubeserviceaks 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: venkataveerakubeserviceaks 
    spec:
      containers:
        - name: venkataveerakubeserviceaks 
          image: vvtestcontainerregistry.azurecr.io/venkataveerakubeserviceaks
          ports:
          - containerPort: 80